### ISSUE TITLE
JapaneseTokenizer stream error

### ISSUE THREAD

**Issue by shatake** [codelibs/fess-suggest#28]
When Crawler is executed,  stream error appeared in solr.log

```
2014-11-08 20:00:24,168 [Thread-2] WARN
jp.sf.fess.suggest.analysis.SuggestTokenizer - JapaneseTokenizer
stream error
java.lang.ArrayIndexOutOfBoundsException: -1
        at org.apache.lucene.analysis.ja.JapaneseTokenizer.backtrace(JapaneseTokenizer.java:1027)
        at org.apache.lucene.analysis.ja.JapaneseTokenizer.parse(JapaneseTokenizer.java:876)
        at org.apache.lucene.analysis.ja.JapaneseTokenizer.incrementToken(JapaneseTokenizer.java:477)
        at jp.sf.fess.suggest.analysis.SuggestTokenizer.initialize(SuggestTokenizer.java:133)
        at jp.sf.fess.suggest.analysis.SuggestTokenizer.reset(SuggestTokenizer.java:274)
        at jp.sf.fess.solr.plugin.suggest.index.DocumentReader.createTokenizer(DocumentReader.java:202)
        at jp.sf.fess.solr.plugin.suggest.index.DocumentReader.next(DocumentReader.java:130)
        at jp.sf.fess.solr.plugin.suggest.SuggestUpdateController$UpdateTask.run(SuggestUpdateController.java:235)
```

**Comment by marevol** [comment]
Closed. fess-suggest 2.0 does not contain this code.
