### ISSUE TITLE
ElasticsearchTimeoutException occurs in SuggestIndexer

### ISSUE THREAD

**Issue by marevol** [codelibs/fess-suggest#33]
```
2016-03-06 01:49:16,004 [pool-1-thread-1] ERROR Failed to update suggest index.
org.elasticsearch.ElasticsearchTimeoutException: Timeout waiting for task.
        at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:70) ~[elasticsearch-2.1.2.jar:2.1.2]
        at org.elasticsearch.action.support.AdapterActionFuture.actionGet(AdapterActionFuture.java:57) ~[elasticsearch-2.1.2.jar:2.1.2]
        at org.codelibs.fess.suggest.index.SuggestIndexer.lambda$indexFromDocument$11(SuggestIndexer.java:201) ~[fess-suggest-2.1.1.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_72]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_72]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_72]
```

**Comment by marevol** [comment]
fixed
